### ISSUE TITLE
Website iframe does not load webapp, even after service restart

### ISSUE THREAD

**Issue by willmacs** [eodms-sgdot/eodms-website#2]
### Expectation

That users would not need to use the workaround and the site loads fine after a service restart.

### Workaround

Users have been using `CTRL+F5` which properly reloads the page and the iframe

### Fix

```html
<script>
var _theframe = document.getElementById("eodmsIframe");
_theframe.contentWindow.location.href = _theframe.src;
</script>
```

**Comment by willmacs** [comment]
deployed to prod

**Comment by kdesjard** [comment]
This is still happening. 

According to https://www.w3schools.com/TAGs/tag_object.asp

"To embed HTML, it is better to use the <iframe> tag"

Probably will need to use a method described in:

https://stackoverflow.com/questions/13477451/can-i-force-a-hard-refresh-on-an-iframe-with-javascript
